name: Generate GitHub Profile Stats Images

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate stats SVG
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/userstats.svg
          include-title: true
          colors: light
          fail-on-error: true
          commit-and-push: true
          commit-message: "Automated change by https://github.com/cicirello/user-statistician"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
